### ISSUE TITLE
zbGuildManager\Roster.lua:384: attempt to index global 'ZRoster' (a nil value)

### ISSUE THREAD

**Issue by gOOvER** [jtrack3d/zbGuildManager#2]
1x zbGuildManager\Roster.lua:384: attempt to index global 'ZRoster' (a nil value)
zbGuildManager\Roster.lua:384: in function `ReconstructLists'
zbGuildManager\zbGuildManager-0.4.1 beta.lua:731: in function `LoadRosterFromServer'
zbGuildManager\zbGuildManager-0.4.1 beta.lua:769: in function <zbGuildManager\zbGuildManager.lua:767>

Locals:
self = <table> {
 RemoveChildNode = <function> defined @zbGuildManager\Roster.lua:469
 HasUnassociated = <function> defined @zbGuildManager\Roster.lua:262
 SortIndex = <function> defined @zbGuildManager\Roster.lua:518
 ActiveCount = 0
 SetRank = <function> defined @zbGuildManager\Roster.lua:513
 SetMain = <function> defined @zbGuildManager\Roster.lua:499
 UpdateHistorySave = <function> defined @zbGuildManager\Roster.lua:568
 AbsentCount = 0
 BuildUnassociatedList = <function> defined @zbGuildManager\Roster.lua:120
 AddCharacter = <function> defined @zbGuildManager\Roster.lua:68
 RemoveCharacter = <function> defined @zbGuildManager\Roster.lua:410
 ReconstructLists = <function> defined @zbGuildManager\Roster.lua:316
 IndexMaxLen = 29
 SemiActiveCount = 0
 SwapMain = <function> defined @zbGuildManager\Roster.lua:523
 players = <table> {
 }
 GetNumAlts = <function> defined @zbGuildManager\Roster.lua:232
 DumpPlayer = <function> defined @zbGuildManager\Roster.lua:134
 GetCharacterIndices = <function> defined @zbGuildManager\Roster.lua:178
 GetFilteredCharacter = <function> defined @zbGuildManager\Roster.lua:204
 GetFilteredIndexCount = <function> defined @zbGuildManager\Roster.lua:208
 GetJoinDate = <function> defined @zbGuildManager\Roster.lua:212
 GetLastLogin = <function> defined @zbGuildManager\Roster.lua:220
 GetCharacter = <function> defined @zbGuildManager\Roster.lua:172
 InactiveCount = 0
 ExportCSV = <function> defined @zbGuildManager\Roster.lua:160
 InsertChildNode = <function> defined @zbGuildManager\Roster.lua:273
 sortIndexBy = "Name"
 BuildFilteredIndex = <function> defined @zbGuildManager\Roster.lua:95
 sortByFunctions = <table> {
 }
 playerIndex = <table> {
 }
}
savedDatesDB = <table> {
 Scheolinchen-Alleria = <table> {
 }
 Antaría-Alleria = <table> {
 }
 Crownfield-Rexxar = <table> {
 }
 Lardner-Alleria = <table> {
 }
 Zodrax-Alleria = <table> {
 }
 Panh-Alleria = <table> {
 }
 Illidanya-Alleria = <table> {
 }
 Durali-Rexxar = <table> {
 }
 Sîrua-Alleria = <table> {
 }
 Krassíx-Alleria = <table> {
 }
 Jeniy-Alleria = <table> {
 }
 Shivar-Alleria = <table> {
 }
 Flôh-Alleria = <table> {
 }
 Chemería-Alleria = <table> {
 }
 Scheola-Alleria = <table> {
 }
 Ferìna-Alleria = <table> {
 }
 Chímêra-Alleria = <table> {
 }
 Kalandur-Alleria = <table> {
 }
 Alinafrau-Rexxar = <table> {
 }
 Koltha-Rexxar = <table> {
 }
 Yriama-Alleria = <table> {
 }
 Aardere-Alleria = <table> {
 }
 Samidy-Alleria = <table> {
 }
 Zulinar-Alleria = <table> {
 }
 Emeraldi-Rexxar = <table> {
 }
 Bärean-Alleria = <table> {
 }
 Alynâ-Rexxar = <table> {
 }
 Scheolâ-Alleria = <table> {
 }
 Yuhika-Alleria = <table> {
 }
 Asag-Alleria = <table> {
 }
 Natoria-Alleria = <table> {
 }
 Lorania-Alleria = <table> {
 }
 Lillinara-Rexxar = <table> {
 }
 Bärbele-Rexxar = <table> {
 }
 Yuhiko-Alleria = <table> {
 }
 Lâcríma-Alleria = <table> {
 }
 Hyleah-Alleria = <table> {
 }
 Thânâtôs-Alleria = <table> {
 }
 Chasse-Alleria = <table> {
 }
 Obelixi-Alleria = <table> {
 }
 Chillgazi-Alleria = <table> {
 }
 Nerin-Alleria = <table> {
 }
 Scheol-Rexxar = <table> {
 }
 Hasele-Rexxar = <table> {
 }
 Zabiria-Alleria = <table> {
 }
 Grantelalf-Alleria = <table> {
 }
 Pheen-Alleria = <table> {
 }
 Adeleé-Alleria = <table> {
 }
 Schêola-Alleria = <table> {
 }
 Yennova-Alleria = <table> {
 }
 Ryuca-Alleria = <table> {
 }
 Chimêrâ-Alleria = <table> {
 }
 Remis-Alleria = <table> {
 }
 Nelayja-Alleria = <table> {
 }
 Sâbrínâ-Alleria = <table> {
 }
 Kuragira-Alleria = <table> {
 }
 Bevina-Rexxar = <table> {
 }
 Sibirien-Rexxar = <table> {
 }
 Chimêra-Alleria = <table> {
 }
 Phelie-Alleria = <table> {
 }
 Fatburner-Alleria = <table> {
 }
 Elitheninja-Rexxar = <table> {
 }
 Avên-

**Comment by jtrack3d** [comment]
Ah ha... I wondered when I made that change what would happen.

**Comment by gOOvER** [comment]
:) I only have this issue, when i open zbGuildManger for the first time. After clicking on Main/Alt it works :)

**Comment by jtrack3d** [comment]
I think I undid this change remotely using the web editor.  

It actually would happen many times during people logging in/out.   What I did was used the CurseForge auto-comment out debug feature and didn't realize that the code was using that.  I will have to modify it to not use that global.  But I can't test that remotely.   So, I just returned it to how it was before quickly.

**Comment by jtrack3d** [comment]
Should be fixed in 0.4.3 Beta
